swagger: "2.0"
info:
  version: "1.0"
  title: LTA Demo API
host: apac-demo1-test.apigee.net
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /charge:
    
    get:
      description: Get Payment Details
      operationId: getdetails
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/getdetailsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/errorResponse"
            

    post:
      description: Initiate Payment
      operationId: initiate
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/initiateResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/errorResponse"   


    put:
      description: Refund Payment
      operationId: refund
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/refundResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/errorResponse"             

    
    delete:
      description: Cancel Payment
      operationId: cancel
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/cancelResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/errorResponse" 
            
definitions:

  getdetailsResponse:
    required:
      - status
    properties:
      status:
        type: string
      currency:
        type: string
      payerparticulars:
        type: string
      payerreference:
        type: string
      payeeparticulars:
        type: string
      payeereference:
        type: string
   
  initiateResponse:
    required:
      - status
    properties:
      status:
        type: string
      paymentid:
        type: string

  refundResponse:
    required:
      - status
    properties:
      status:
        type: string
      paymentid:
        type: string

  cancelResponse:
    required:
      - status
    properties:
      status:
        type: string
      paymentid:
        type: string
      paymentstatus:
        type: string
        
  errorResponse:
    required:
      - status
    properties:
      status:
        type: string